import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "J.K. Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link rel="icon" href="/logo.jpg" type="image/x-icon"  />
    </head>
      <body className="overflow-x-idden">
        <Header />
        {children}
      </body>
    </html>
  );
}
